export const YINYANG_NAME = {
  '0': '阴',
  '1': '阳',
};

export type TrigramItem = { key: string; name: string; nick: string; wuxing: string; symbol: string };

export const TRIGRAM: Record<string, TrigramItem> = {
  '000': { key: '000', name: '坤', nick: '地', wuxing: '土', symbol: '☷' },
  '001': { key: '001', name: '艮', nick: '山', wuxing: '土', symbol: '☶' },
  '010': { key: '010', name: '坎', nick: '水', wuxing: '水', symbol: '☵' },
  '011': { key: '011', name: '巽', nick: '泽', wuxing: '木', symbol: '☴' },
  '100': { key: '100', name: '震', nick: '雷', wuxing: '木', symbol: '☳' },
  '101': { key: '101', name: '离', nick: '火', wuxing: '火', symbol: '☲' },
  '110': { key: '110', name: '兑', nick: '风', wuxing: '金', symbol: '☱' },
  '111': { key: '111', name: '乾', nick: '天', wuxing: '金', symbol: '☰' },
};

export type HexagramItem = {
  key: string;
  gua: string;
  name: string;
  sequence: number;
  text: string;
  symbol: string;
  palace: string;
  shi: number;
  ying: number;
  ganzhi: string[];
  relation: string[];
  judgement: string;
  lineTexts: { label: string; text: string }[];
  wuxing: string;
};

export const HEXAGRAM: Record<string, HexagramItem> = {
  '100000': {
    key: '100000',
    gua: '复',
    name: '地雷复',
    sequence: 24,
    text: '雷在地中，复；先王以至日闭关，商旅不行，后不省方。',
    symbol: '䷗',
    palace: '000000',
    wuxing: '土',
    shi: 0,
    ying: 3,
    ganzhi: ['庚子', '庚寅', '庚辰', '癸丑', '癸亥', '癸酉'],
    relation: ['妻财', '官鬼', '兄弟', '兄弟', '妻财', '子孙'],
    judgement: '复：亨。出入无疾，朋来无咎。反复其道，七日来复，利有攸往。',
    lineTexts: [
      { label: '初九', text: '不远复，无祗悔，元吉。' },
      { label: '六二', text: '休复，吉。' },
      { label: '六三', text: '频复，厉，无咎。' },
      { label: '六四', text: '中行独复。' },
      { label: '六五', text: '敦复，无悔。' },
      { label: '上六', text: '迷复，凶，有灾眚。用行师，终有大败；以其国君凶，至于十年不克征。' },
    ],
  },
  '100001': {
    key: '100001',
    gua: '颐',
    name: '山雷颐',
    sequence: 27,
    text: '山下有雷，颐；君子以慎言语，节饮食。',
    symbol: '䷚',
    palace: '011011',
    wuxing: '木',
    shi: 3,
    ying: 0,
    ganzhi: ['庚子', '庚寅', '庚辰', '丙戌', '丙子', '丙寅'],
    relation: ['父母', '兄弟', '妻财', '妻财', '父母', '兄弟'],
    judgement: '颐：贞吉。观颐，自求口实。',
    lineTexts: [
      { label: '初九', text: '舍尔灵龟，观我朵颐，凶。' },
      { label: '六二', text: '颠颐，拂经，于丘颐，征凶。' },
      { label: '六三', text: '拂颐，贞凶，十年勿用，无攸利。' },
      { label: '六四', text: '颠颐，吉。虎视眈眈，其欲逐逐，无咎。' },
      { label: '六五', text: '拂经，居贞吉，不可涉大川。' },
      { label: '上九', text: '由颐，厉吉，利涉大川。' },
    ],
  },
  '100010': {
    key: '100010',
    gua: '屯',
    name: '水雷屯',
    sequence: 3,
    text: '云雷屯，君子以经纶。',
    symbol: '䷂',
    palace: '010010',
    wuxing: '水',
    shi: 1,
    ying: 4,
    ganzhi: ['庚子', '庚寅', '庚辰', '戊申', '戊戌', '戊子'],
    relation: ['兄弟', '子孙', '官鬼', '父母', '官鬼', '兄弟'],
    judgement: '屯：元，亨，利，贞。勿用有攸往，利建侯。',
    lineTexts: [
      { label: '初九', text: '磐桓，利居贞，利建侯。' },
      { label: '六二', text: '屯如邅如，乘马班如。匪寇，婚媾。女子贞不字，十年乃字。' },
      { label: '六三', text: '即鹿无虞，惟入于林中，君子几，不如舍，往吝。' },
      { label: '六四', text: '乘马班如，求婚媾，往吉，无不利。' },
      { label: '九五', text: '屯其膏，小贞吉，大贞凶。' },
      { label: '上六', text: '乘马班如，泣血涟如。' },
    ],
  },
  '100011': {
    key: '100011',
    gua: '益',
    name: '风雷益',
    sequence: 42,
    text: '风雷，益；君子以见善则迁，有过则改。',
    symbol: '䷩',
    palace: '011011',
    wuxing: '木',
    shi: 2,
    ying: 5,
    ganzhi: ['庚子', '庚寅', '庚辰', '辛未', '辛巳', '辛卯'],
    relation: ['父母', '兄弟', '妻财', '妻财', '子孙', '兄弟'],
    judgement: '益：利有攸往，利涉大川。',
    lineTexts: [
      { label: '初九', text: '利用为大作，元吉，无咎。' },
      { label: '六二', text: '或益之十朋之龟，弗克违，永贞吉。王用享于帝，吉。' },
      { label: '六三', text: '益之用凶事，无咎。有孚中行，告公用圭。' },
      { label: '六四', text: '中行，告公从。利用为依迁国。' },
      { label: '九五', text: '有孚惠心，勿问元吉。有孚惠我德。' },
      { label: '上九', text: '莫益之，或击之，立心勿恒，凶。' },
    ],
  },
  '100100': {
    key: '100100',
    gua: '震',
    name: '震为雷',
    sequence: 51,
    text: '洊雷，震；君子以恐惧修省。',
    symbol: '䷲',
    palace: '100100',
    wuxing: '木',
    shi: 5,
    ying: 2,
    ganzhi: ['庚子', '庚寅', '庚辰', '庚午', '庚申', '庚戌'],
    relation: ['父母', '兄弟', '妻财', '子孙', '官鬼', '妻财'],
    judgement: '震：亨。震来虩虩，笑言哑哑；震惊百里，不丧匕鬯。',
    lineTexts: [
      { label: '初九', text: '震来虩虩，后笑言哑哑，吉。' },
      { label: '六二', text: '震来厉，亿丧贝，跻于九陵，勿逐，七日得。' },
      { label: '六三', text: '震苏苏，震行无眚。' },
      { label: '九四', text: '震遂泥。' },
      { label: '六五', text: '震往来厉，亿无丧，有事。' },
      { label: '上六', text: '震索索，视矍矍，征凶。震不于其躬，于其邻，无咎。婚媾有言。' },
    ],
  },
  '100101': {
    key: '100101',
    gua: '噬嗑',
    name: '火雷噬嗑',
    sequence: 21,
    text: '雷电，噬嗑；先王以明罚敕法。',
    symbol: '䷔',
    palace: '011011',
    wuxing: '木',
    shi: 4,
    ying: 1,
    ganzhi: ['庚子', '庚寅', '庚辰', '己酉', '己未', '己巳'],
    relation: ['父母', '兄弟', '妻财', '官鬼', '妻财', '子孙'],
    judgement: '噬嗑：亨。利用狱。',
    lineTexts: [
      { label: '初九', text: '屦校灭趾，无咎。' },
      { label: '六二', text: '噬肤灭鼻，无咎。' },
      { label: '六三', text: '噬腊肉，遇毒；小吝，无咎。' },
      { label: '九四', text: '噬乾胏，得金矢，利艰贞，吉。' },
      { label: '六五', text: '噬乾肉，得黄金，贞厉，无咎。' },
      { label: '上九', text: '何校灭耳，凶。' },
    ],
  },
  '100110': {
    key: '100110',
    gua: '随',
    name: '泽雷随',
    sequence: 17,
    text: '泽中有雷，随；君子以向晦入宴息。',
    symbol: '䷐',
    palace: '100100',
    wuxing: '木',
    shi: 2,
    ying: 5,
    ganzhi: ['庚子', '庚寅', '庚辰', '丁亥', '丁酉', '丁未'],
    relation: ['父母', '兄弟', '妻财', '父母', '官鬼', '妻财'],
    judgement: '随：元亨，利贞，无咎。',
    lineTexts: [
      { label: '初九', text: '官有渝，贞吉。出门交有功。' },
      { label: '六二', text: '系小子，失丈夫。' },
      { label: '六三', text: '系丈夫，失小子。随有求得，利居贞。' },
      { label: '九四', text: '随有获，贞凶。有孚在道，以明，何咎。' },
      { label: '九五', text: '孚于嘉，吉。' },
      { label: '上六', text: '拘系之，乃从维之。王用亨于西山。' },
    ],
  },
  '100111': {
    key: '100111',
    gua: '无妄',
    name: '天雷无妄',
    sequence: 25,
    text: '天下雷行，物与无妄；先王以茂对时育万物。',
    symbol: '䷘',
    palace: '011011',
    wuxing: '木',
    shi: 3,
    ying: 0,
    ganzhi: ['庚子', '庚寅', '庚辰', '壬午', '壬申', '壬戌'],
    relation: ['父母', '兄弟', '妻财', '子孙', '官鬼', '妻财'],
    judgement: '无妄：元亨，利贞。其匪正有眚，不利有攸往。',
    lineTexts: [
      { label: '初九', text: '无妄，往吉。' },
      { label: '六二', text: '不耕获，不菑畬，则利有攸往。' },
      { label: '六三', text: '无妄之灾，或系之牛，行人之得，邑人之灾。' },
      { label: '九四', text: '可贞，无咎。' },
      { label: '九五', text: '无妄之疾，勿药有喜。' },
      { label: '上九', text: '无妄，行有眚，无攸利。' },
    ],
  },
  '101000': {
    key: '101000',
    gua: '明夷',
    name: '地火明夷',
    sequence: 36,
    text: '明入地中，明夷；君子以莅众用晦而明。',
    symbol: '䷣',
    palace: '010010',
    wuxing: '水',
    shi: 3,
    ying: 0,
    ganzhi: ['己卯', '己丑', '己亥', '癸丑', '癸亥', '癸酉'],
    relation: ['子孙', '官鬼', '兄弟', '官鬼', '兄弟', '父母'],
    judgement: '明夷：利艰贞。',
    lineTexts: [
      { label: '初九', text: '明夷于飞，垂其翼。君子于行，三日不食，有攸往，主人有言。' },
      { label: '六二', text: '明夷，夷于左股，用拯马壮，吉。' },
      { label: '九三', text: '明夷于南狩，得其大首，不可疾贞。' },
      { label: '六四', text: '入于左腹，获明夷之心，于出门庭。' },
      { label: '六五', text: '箕子之明夷，利贞。' },
      { label: '上六', text: '不明晦，初登于天，后入于地。' },
    ],
  },
  '101001': {
    key: '101001',
    gua: '贲',
    name: '山火贲',
    sequence: 22,
    text: '山下有火，贲；君子以明庶政，无敢折狱。',
    symbol: '䷕',
    palace: '001001',
    wuxing: '土',
    shi: 0,
    ying: 3,
    ganzhi: ['己卯', '己丑', '己亥', '丙戌', '丙子', '丙寅'],
    relation: ['官鬼', '兄弟', '妻财', '兄弟', '妻财', '官鬼'],
    judgement: '贲：亨。小利有攸往。',
    lineTexts: [
      { label: '初九', text: '贲其趾，舍车而徒。' },
      { label: '六二', text: '贲其须。' },
      { label: '九三', text: '贲如，濡如，永贞吉。' },
      { label: '六四', text: '贲如，皤如，白马翰如，匪寇婚媾。' },
      { label: '六五', text: '贲于丘园，束帛戋戋，吝，终吉。' },
      { label: '上九', text: '白贲，无咎。' },
    ],
  },
  '101010': {
    key: '101010',
    gua: '既济',
    name: '水火既济',
    sequence: 63,
    text: '水在火上，既济；君子以思患而豫防之。',
    symbol: '䷾',
    palace: '010010',
    wuxing: '水',
    shi: 2,
    ying: 5,
    ganzhi: ['己卯', '己丑', '己亥', '戊申', '戊戌', '戊子'],
    relation: ['子孙', '官鬼', '兄弟', '父母', '官鬼', '兄弟'],
    judgement: '既济：亨小，利贞，初吉终乱。',
    lineTexts: [
      { label: '初九', text: '曳其轮，濡其尾，无咎。' },
      { label: '六二', text: '妇丧其茀，勿逐，七日得。' },
      { label: '九三', text: '高宗伐鬼方，三年克之，小人勿用。' },
      { label: '六四', text: '繻有衣袽，终日戒。' },
      { label: '九五', text: '东邻杀牛，不如西邻之禴祭，实受其福。' },
      { label: '上六', text: '濡其首，厉。' },
    ],
  },
  '101011': {
    key: '101011',
    gua: '家人',
    name: '风火家人',
    sequence: 37,
    text: '风自火出，家人；君子以言有物而行有恒。',
    symbol: '䷤',
    palace: '011011',
    wuxing: '木',
    shi: 1,
    ying: 4,
    ganzhi: ['己卯', '己丑', '己亥', '辛未', '辛巳', '辛卯'],
    relation: ['兄弟', '妻财', '父母', '妻财', '子孙', '兄弟'],
    judgement: '家人：利女贞。',
    lineTexts: [
      { label: '初九', text: '闲有家，悔亡。' },
      { label: '六二', text: '无攸遂，在中馈，贞吉。' },
      { label: '九三', text: '家人嗃嗃，悔厉吉；妇子嘻嘻，终吝。' },
      { label: '六四', text: '富家，大吉。' },
      { label: '九五', text: '王假有家，勿恤，吉。' },
      { label: '上九', text: '有孚威如，终吉。' },
    ],
  },
  '101100': {
    key: '101100',
    gua: '丰',
    name: '雷火丰',
    sequence: 55,
    text: '雷电皆至，丰；君子以折狱致刑。',
    symbol: '䷶',
    palace: '010010',
    wuxing: '水',
    shi: 4,
    ying: 1,
    ganzhi: ['己卯', '己丑', '己亥', '庚午', '庚申', '庚戌'],
    relation: ['子孙', '官鬼', '兄弟', '妻财', '父母', '官鬼'],
    judgement: '丰：亨。王假之，勿忧，宜日中。',
    lineTexts: [
      { label: '初九', text: '遇其配主，虽旬无咎，往有尚。' },
      { label: '六二', text: '丰其蔀，日中见斗；往得疑疾，有孚发若，吉。' },
      { label: '九三', text: '丰其沛，日中见昧；折其右肱，无咎。' },
      { label: '九四', text: '丰其蔀，日中见斗；遇其夷主，吉。' },
      { label: '六五', text: '来章，有庆誉，吉。' },
      { label: '上六', text: '丰其屋，蔀其家，窥其户，阒其无人，三岁不觌，凶。' },
    ],
  },
  '101101': {
    key: '101101',
    gua: '离',
    name: '离为火',
    sequence: 30,
    text: '明两作，离；大人以继明照于四方。',
    symbol: '䷝',
    palace: '101101',
    wuxing: '火',
    shi: 5,
    ying: 2,
    ganzhi: ['己卯', '己丑', '己亥', '己酉', '己未', '己巳'],
    relation: ['父母', '子孙', '官鬼', '妻财', '子孙', '兄弟'],
    judgement: '离：利贞，亨。畜牝牛，吉。',
    lineTexts: [
      { label: '初九', text: '履错然，敬之，无咎。' },
      { label: '六二', text: '黄离，元吉。' },
      { label: '九三', text: '日昃之离，不鼓缶而歌，则大耋之嗟，凶。' },
      { label: '九四', text: '突如其来如，焚如，死如，弃如。' },
      { label: '六五', text: '出涕沱若，戚嗟若，吉。' },
      { label: '上九', text: '王用出征，有嘉折首，获匪其丑，无咎。' },
    ],
  },
  '101110': {
    key: '101110',
    gua: '革',
    name: '泽火革',
    sequence: 49,
    text: '泽中有火，革；君子以治历明时。',
    symbol: '䷰',
    palace: '010010',
    wuxing: '水',
    shi: 3,
    ying: 0,
    ganzhi: ['己卯', '己丑', '己亥', '丁亥', '丁酉', '丁未'],
    relation: ['子孙', '官鬼', '兄弟', '兄弟', '父母', '官鬼'],
    judgement: '革：己日乃孚，元亨，利贞，悔亡。',
    lineTexts: [
      { label: '初九', text: '巩用黄牛之革。' },
      { label: '六二', text: '己日乃革之，征吉，无咎。' },
      { label: '九三', text: '征凶，贞厉。革言三就，有孚。' },
      { label: '九四', text: '悔亡，有孚改命，吉。' },
      { label: '九五', text: '大人虎变，未占有孚。' },
      { label: '上六', text: '君子豹变，小人革面，征凶，居贞吉。' },
    ],
  },
  '101111': {
    key: '101111',
    gua: '同人',
    name: '天火同人',
    sequence: 13,
    text: '天与火，同人；君子以类族辨物。',
    symbol: '䷌',
    palace: '101101',
    wuxing: '火',
    shi: 2,
    ying: 5,
    ganzhi: ['己卯', '己丑', '己亥', '壬午', '壬申', '壬戌'],
    relation: ['父母', '子孙', '官鬼', '兄弟', '妻财', '子孙'],
    judgement: '同人：同人于野，亨。利涉大川，利君子贞。',
    lineTexts: [
      { label: '初九', text: '同人于门，无咎。' },
      { label: '六二', text: '同人于宗，吝。' },
      { label: '九三', text: '伏戎于莽，升其高陵，三岁不兴。' },
      { label: '九四', text: '乘其墉，弗克攻，吉。' },
      { label: '九五', text: '同人，先号咷而后笑。大师克，相遇。' },
      { label: '上九', text: '同人于郊，无悔。' },
    ],
  },
  '110000': {
    key: '110000',
    gua: '临',
    name: '地泽临',
    sequence: 19,
    text: '泽上有地，临；君子以教思无穷，容保民无疆。',
    symbol: '䷒',
    palace: '000000',
    wuxing: '土',
    shi: 1,
    ying: 4,
    ganzhi: ['丁巳', '丁卯', '丁丑', '癸丑', '癸亥', '癸酉'],
    relation: ['父母', '官鬼', '兄弟', '兄弟', '妻财', '子孙'],
    judgement: '临：元亨，利贞。至于八月有凶。',
    lineTexts: [
      { label: '初九', text: '咸临，贞吉。' },
      { label: '九二', text: '咸临，吉，无不利。' },
      { label: '六三', text: '甘临，无攸利。既忧之，无咎。' },
      { label: '六四', text: '至临，无咎。' },
      { label: '六五', text: '知临，大君之宜，吉。' },
      { label: '上六', text: '敦临，吉，无咎。' },
    ],
  },
  '110001': {
    key: '110001',
    gua: '损',
    name: '山泽损',
    sequence: 41,
    text: '山下有泽，损；君子以惩忿窒欲。',
    symbol: '䷨',
    palace: '001001',
    wuxing: '土',
    shi: 2,
    ying: 5,
    ganzhi: ['丁巳', '丁卯', '丁丑', '丙戌', '丙子', '丙寅'],
    relation: ['父母', '官鬼', '兄弟', '兄弟', '妻财', '官鬼'],
    judgement: '损：有孚，元吉，无咎，可贞，利有攸往。曷之用？二簋可用享。',
    lineTexts: [
      { label: '初九', text: '已事遄往，无咎，酌损之。' },
      { label: '九二', text: '利贞，征凶，弗损益之。' },
      { label: '六三', text: '三人行，则损一人；一人行，则得其友。' },
      { label: '六四', text: '损其疾，使遄有喜，无咎。' },
      { label: '六五', text: '或益之十朋之龟，弗克违，元吉。' },
      { label: '上九', text: '弗损益之，无咎，贞吉，利有攸往，得臣无家。' },
    ],
  },
  '110010': {
    key: '110010',
    gua: '节',
    name: '水泽节',
    sequence: 60,
    text: '泽上有水，节；君子以制数度，议德行。',
    symbol: '䷻',
    palace: '010010',
    wuxing: '水',
    shi: 0,
    ying: 3,
    ganzhi: ['丁巳', '丁卯', '丁丑', '戊申', '戊戌', '戊子'],
    relation: ['妻财', '子孙', '官鬼', '父母', '官鬼', '兄弟'],
    judgement: '节：亨。苦节不可贞。',
    lineTexts: [
      { label: '初九', text: '不出户庭，无咎。' },
      { label: '九二', text: '不出门庭，凶。' },
      { label: '六三', text: '不节若，则嗟若，无咎。' },
      { label: '六四', text: '安节，亨。' },
      { label: '九五', text: '甘节，吉；往有尚。' },
      { label: '上六', text: '苦节，贞凶，悔亡。' },
    ],
  },
  '110011': {
    key: '110011',
    gua: '中孚',
    name: '风泽中孚',
    sequence: 61,
    text: '泽上有风，中孚；君子以议狱缓死。',
    symbol: '䷼',
    palace: '001001',
    wuxing: '土',
    shi: 3,
    ying: 0,
    ganzhi: ['丁巳', '丁卯', '丁丑', '辛未', '辛巳', '辛卯'],
    relation: ['父母', '官鬼', '兄弟', '兄弟', '父母', '官鬼'],
    judgement: '中孚：豚鱼吉，利涉大川，利贞。',
    lineTexts: [
      { label: '初九', text: '虞吉，有它不燕。' },
      { label: '九二', text: '鸣鹤在阴，其子和之；我有好爵，吾与尔靡之。' },
      { label: '六三', text: '得敌，或鼓或罢，或泣或歌。' },
      { label: '六四', text: '月几望，马匹亡，无咎。' },
      { label: '九五', text: '有孚挛如，无咎。' },
      { label: '上九', text: '翰音登于天，贞凶。' },
    ],
  },
  '110100': {
    key: '110100',
    gua: '归妹',
    name: '雷泽归妹',
    sequence: 54,
    text: '泽上有雷，归妹；君子以永终知敝。',
    symbol: '䷵',
    palace: '110110',
    wuxing: '金',
    shi: 2,
    ying: 5,
    ganzhi: ['丁巳', '丁卯', '丁丑', '庚午', '庚申', '庚戌'],
    relation: ['官鬼', '妻财', '父母', '官鬼', '兄弟', '父母'],
    judgement: '归妹：征凶，无攸利。',
    lineTexts: [
      { label: '初九', text: '归妹以娣，跛能履，征吉。' },
      { label: '九二', text: '眇能视，利幽人之贞。' },
      { label: '六三', text: '归妹以须，反归以娣。' },
      { label: '九四', text: '归妹愆期，迟归有时。' },
      { label: '六五', text: '帝乙归妹，其君之袂，不如其娣之袂良；月几望，吉。' },
      { label: '上六', text: '女承筐无实，士刲羊无血，无攸利。' },
    ],
  },
  '110101': {
    key: '110101',
    gua: '睽',
    name: '火泽睽',
    sequence: 38,
    text: '上火下泽，睽；君子以同而异。',
    symbol: '䷥',
    palace: '001001',
    wuxing: '土',
    shi: 3,
    ying: 0,
    ganzhi: ['丁巳', '丁卯', '丁丑', '己酉', '己未', '己巳'],
    relation: ['父母', '官鬼', '兄弟', '子孙', '兄弟', '父母'],
    judgement: '睽：小事吉。',
    lineTexts: [
      { label: '初九', text: '悔亡。丧马勿逐，自复；见恶人，无咎。' },
      { label: '九二', text: '遇主于巷，无咎。' },
      { label: '六三', text: '见舆曳，其牛掣，其人天且劓，无初有终。' },
      { label: '九四', text: '睽孤，遇元夫，交孚，厉无咎。' },
      { label: '六五', text: '悔亡。厥宗噬肤，往何咎。' },
      { label: '上九', text: '睽孤。见豕负涂，载鬼一车，先张之弧，后说之弧；匪寇婚媾，往遇雨则吉。' },
    ],
  },
  '110110': {
    key: '110110',
    gua: '泽',
    name: '兑为泽',
    sequence: 58,
    text: '丽泽，兑；君子以朋友讲习。',
    symbol: '䷹',
    palace: '110110',
    wuxing: '金',
    shi: 5,
    ying: 2,
    ganzhi: ['丁巳', '丁卯', '丁丑', '丁亥', '丁酉', '丁未'],
    relation: ['官鬼', '妻财', '父母', '子孙', '兄弟', '父母'],
    judgement: '兑：亨，利贞。',
    lineTexts: [
      { label: '初九', text: '和兑，吉。' },
      { label: '九二', text: '孚兑，吉，悔亡。' },
      { label: '六三', text: '来兑，凶。' },
      { label: '九四', text: '商兑，未宁，介疾有喜。' },
      { label: '九五', text: '孚于剥，有厉。' },
      { label: '上六', text: '引兑。' },
    ],
  },
  '110111': {
    key: '110111',
    gua: '履',
    name: '天泽履',
    sequence: 10,
    text: '上天下泽，履；君子以辨上下，定民志。',
    symbol: '䷉',
    palace: '001001',
    wuxing: '土',
    shi: 4,
    ying: 1,
    ganzhi: ['丁巳', '丁卯', '丁丑', '壬午', '壬申', '壬戌'],
    relation: ['父母', '官鬼', '兄弟', '父母', '子孙', '兄弟'],
    judgement: '履：履虎尾，不咥人，亨。',
    lineTexts: [
      { label: '初九', text: '素履，往无咎。' },
      { label: '九二', text: '履道坦坦，幽人贞吉。' },
      { label: '六三', text: '眇能视，跛能履，履虎尾，咥人，凶。武人为于大君。' },
      { label: '九四', text: '履虎尾，愬愬，终吉。' },
      { label: '九五', text: '夬履，贞厉。' },
      { label: '上九', text: '视履考祥，其旋元吉。' },
    ],
  },
  '111000': {
    key: '111000',
    gua: '泰',
    name: '天地泰',
    sequence: 11,
    text: '天地交，泰；后以财成天地之道，辅相天地之宜，以左右民。',
    symbol: '䷊',
    palace: '000000',
    wuxing: '土',
    shi: 2,
    ying: 5,
    ganzhi: ['甲子', '甲寅', '甲辰', '癸丑', '癸亥', '癸酉'],
    relation: ['妻财', '官鬼', '兄弟', '兄弟', '妻财', '子孙'],
    judgement: '泰：小往大来，吉，亨。',
    lineTexts: [
      { label: '初九', text: '拔茅茹，以其汇，征吉。' },
      { label: '九二', text: '包荒，用冯河，不遐遗；朋亡，得尚于中行。' },
      { label: '九三', text: '无平不陂，无往不复。艰贞，无咎。勿恤其孚，于食有福。' },
      { label: '六四', text: '翩翩，不富以其邻，不戒以孚。' },
      { label: '六五', text: '帝乙归妹，以祉元吉。' },
      { label: '上六', text: '城复于隍，勿用师。自邑告命，贞吝。' },
    ],
  },
  '111001': {
    key: '111001',
    gua: '大畜',
    name: '山天大畜',
    sequence: 26,
    text: '天在山中，大畜；君子以多识前言往行，以畜其德。',
    symbol: '䷙',
    palace: '001001',
    wuxing: '土',
    shi: 1,
    ying: 4,
    ganzhi: ['甲子', '甲寅', '甲辰', '丙戌', '丙子', '丙寅'],
    relation: ['妻财', '官鬼', '兄弟', '兄弟', '妻财', '官鬼'],
    judgement: '大畜：利贞，不家食吉，利涉大川。',
    lineTexts: [
      { label: '初九', text: '有厉利已。' },
      { label: '九二', text: '舆说輹。' },
      { label: '九三', text: '良马逐，利艰贞。曰闲舆卫，利有攸往。' },
      { label: '六四', text: '童牛之牿，元吉。' },
      { label: '六五', text: '豶豕之牙，吉。' },
      { label: '上九', text: '何天之衢，亨。' },
    ],
  },
  '111010': {
    key: '111010',
    gua: '需',
    name: '水天需',
    sequence: 5,
    text: '云上于天，需；君子以饮食宴乐。',
    symbol: '䷄',
    palace: '000000',
    wuxing: '土',
    shi: 3,
    ying: 0,
    ganzhi: ['甲子', '甲寅', '甲辰', '戊申', '戊戌', '戊子'],
    relation: ['妻财', '官鬼', '兄弟', '子孙', '兄弟', '妻财'],
    judgement: '需：有孚，光亨，贞吉。利涉大川。',
    lineTexts: [
      { label: '初九', text: '需于郊，利用恒，无咎。' },
      { label: '九二', text: '需于沙，小有言，终吉。' },
      { label: '九三', text: '需于泥，致寇至。' },
      { label: '六四', text: '需于血，出自穴。' },
      { label: '九五', text: '需于酒食，贞吉。' },
      { label: '上六', text: '入于穴，有不速之客三人来，敬之，终吉。' },
    ],
  },
  '111011': {
    key: '111011',
    gua: '小畜',
    name: '风天小畜',
    sequence: 9,
    text: '风行天上，小畜；君子以懿文德。',
    symbol: '䷈',
    palace: '011011',
    wuxing: '木',
    shi: 0,
    ying: 3,
    ganzhi: ['甲子', '甲寅', '甲辰', '辛未', '辛巳', '辛卯'],
    relation: ['父母', '兄弟', '妻财', '妻财', '子孙', '兄弟'],
    judgement: '小畜：亨。密云不雨，自我西郊。',
    lineTexts: [
      { label: '初九', text: '复自道，何其咎，吉。' },
      { label: '九二', text: '牵复，吉。' },
      { label: '九三', text: '舆说辐，夫妻反目。' },
      { label: '六四', text: '有孚，血去惕出，无咎。' },
      { label: '九五', text: '有孚挛如，富以其邻。' },
      { label: '上九', text: '既雨既处，尚德载，妇贞厉。月几望，君子征凶。' },
    ],
  },
  '111100': {
    key: '111100',
    gua: '大壮',
    name: '雷天大壮',
    sequence: 34,
    text: '雷在天上，大壮；君子以非礼弗履。',
    symbol: '䷡',
    palace: '000000',
    wuxing: '土',
    shi: 3,
    ying: 0,
    ganzhi: ['甲子', '甲寅', '甲辰', '庚午', '庚申', '庚戌'],
    relation: ['妻财', '官鬼', '兄弟', '父母', '子孙', '兄弟'],
    judgement: '大壮：利贞。',
    lineTexts: [
      { label: '初九', text: '壮于趾，征凶，有孚。' },
      { label: '九二', text: '贞吉。' },
      { label: '九三', text: '小人用壮，君子用罔，贞厉。羝羊触藩，羸其角。' },
      { label: '九四', text: '贞吉，悔亡。藩决不羸，壮于大舆之輹。' },
      { label: '六五', text: '丧羊于易，无悔。' },
      { label: '上六', text: '羝羊触藩，不能退，不能遂，无攸利，艰则吉。' },
    ],
  },
  '111101': {
    key: '111101',
    gua: '大有',
    name: '火天大有',
    sequence: 14,
    text: '火在天上，大有；君子以遏恶扬善，顺天休命。',
    symbol: '䷍',
    palace: '111111',
    wuxing: '金',
    shi: 2,
    ying: 5,
    ganzhi: ['甲子', '甲寅', '甲辰', '己酉', '己未', '己巳'],
    relation: ['子孙', '妻财', '父母', '兄弟', '父母', '官鬼'],
    judgement: '大有：元亨。',
    lineTexts: [
      { label: '初九', text: '无交害，匪咎，艰则无咎。' },
      { label: '九二', text: '大车以载，有攸往，无咎。' },
      { label: '九三', text: '公用亨于天子，小人弗克。' },
      { label: '九四', text: '匪其彭，无咎。' },
      { label: '六五', text: '厥孚交如，威如，吉。' },
      { label: '上九', text: '自天佑之，吉无不利。' },
    ],
  },
  '111110': {
    key: '111110',
    gua: '夬',
    name: '泽天夬',
    sequence: 43,
    text: '泽上于天，夬；君子以施禄及下，居德则忌。',
    symbol: '䷪',
    palace: '000000',
    wuxing: '土',
    shi: 4,
    ying: 1,
    ganzhi: ['甲子', '甲寅', '甲辰', '丁亥', '丁酉', '丁未'],
    relation: ['妻财', '官鬼', '兄弟', '妻财', '子孙', '兄弟'],
    judgement: '夬：扬于王庭，孚号，有厉。告自邑，不利即戎，利有攸往。',
    lineTexts: [
      { label: '初九', text: '壮于前趾，往不胜为咎。' },
      { label: '九二', text: '惕号，莫夜有戎，勿恤。' },
      { label: '九三', text: '壮于頄，有凶。君子夬夬，独行遇雨，若濡有愠，无咎。' },
      { label: '九四', text: '臀无肤，其行次且。牵羊悔亡，闻言不信。' },
      { label: '九五', text: '苋陆夬夬，中行无咎。' },
      { label: '上六', text: '无号，终有凶。' },
    ],
  },
  '111111': {
    key: '111111',
    gua: '乾',
    name: '乾为天',
    sequence: 1,
    text: '天行健，君子以自强不息。',
    symbol: '䷀',
    palace: '111111',
    wuxing: '金',
    shi: 5,
    ying: 2,
    ganzhi: ['甲子', '甲寅', '甲辰', '壬午', '壬申', '壬戌'],
    relation: ['子孙', '妻财', '父母', '官鬼', '兄弟', '父母'],
    judgement: '乾：元，亨，利，贞。',
    lineTexts: [
      { label: '初九', text: '潜龙，勿用。' },
      { label: '九二', text: '见龙在田，利见大人。' },
      { label: '九三', text: '君子终日乾乾，夕惕若，厉，无咎。' },
      { label: '九四', text: '或跃在渊，无咎。' },
      { label: '九五', text: '飞龙在天，利见大人。' },
      { label: '上九', text: '亢龙，有悔。' },
    ],
  },
  '000000': {
    key: '000000',
    gua: '坤',
    name: '坤为地',
    sequence: 2,
    text: '地势坤，君子以厚德载物。',
    symbol: '䷁',
    palace: '000000',
    wuxing: '土',
    shi: 5,
    ying: 2,
    ganzhi: ['乙未', '乙巳', '乙卯', '癸丑', '癸亥', '癸酉'],
    relation: ['兄弟', '父母', '官鬼', '兄弟', '妻财', '子孙'],
    judgement: '坤：元，亨，利牝马之贞。君子有攸往，先迷后得主，利。西南得朋，东北丧朋。安贞，吉。',
    lineTexts: [
      { label: '初六', text: '履霜，坚冰至。' },
      { label: '六二', text: '直，方，大，不习无不利。' },
      { label: '六三', text: '含章可贞。或从王事，无成有终。' },
      { label: '六四', text: '括囊，无咎，无誉。' },
      { label: '六五', text: '黄裳，元吉。' },
      { label: '上六', text: '龙战于野，其血玄黄。' },
    ],
  },
  '010001': {
    key: '010001',
    gua: '蒙',
    name: '山水蒙',
    sequence: 4,
    text: '山下出泉，蒙；君子以果行育德。',
    symbol: '䷃',
    palace: '101101',
    wuxing: '火',
    shi: 3,
    ying: 0,
    ganzhi: ['戊寅', '戊辰', '戊午', '丙戌', '丙子', '丙寅'],
    relation: ['父母', '子孙', '兄弟', '子孙', '官鬼', '父母'],
    judgement: '蒙：亨。匪我求童蒙，童蒙求我。初筮告，再三渎，渎则不告。利贞。',
    lineTexts: [
      { label: '初六', text: '发蒙，利用刑人，用说桎梏，以往吝。' },
      { label: '九二', text: '包蒙，吉。纳妇，吉；子克家。' },
      { label: '六三', text: '勿用取女，见金夫，不有躬，无攸利。' },
      { label: '六四', text: '困蒙，吝。' },
      { label: '六五', text: '童蒙，吉。' },
      { label: '上九', text: '击蒙，不利为寇，利御寇。' },
    ],
  },
  '010111': {
    key: '010111',
    gua: '讼',
    name: '天水讼',
    sequence: 6,
    text: '天与水违行，讼；君子以作事谋始。',
    symbol: '䷅',
    palace: '101101',
    wuxing: '火',
    shi: 3,
    ying: 0,
    ganzhi: ['戊寅', '戊辰', '戊午', '壬午', '壬申', '壬戌'],
    relation: ['父母', '子孙', '兄弟', '兄弟', '妻财', '子孙'],
    judgement: '讼：有孚，窒惕，中吉，终凶。利见大人，不利涉大川。',
    lineTexts: [
      { label: '初六', text: '不永所事，小有言，终吉。' },
      { label: '九二', text: '不克讼，归而逋，其邑人三百户，无眚。' },
      { label: '六三', text: '食旧德，贞厉，终吉。或从王事，无成。' },
      { label: '九四', text: '不克讼，复即命，渝安贞，吉。' },
      { label: '九五', text: '讼，元吉。' },
      { label: '上九', text: '或锡之鞶带，终朝三褫之。' },
    ],
  },
  '010000': {
    key: '010000',
    gua: '师',
    name: '地水师',
    sequence: 7,
    text: '地中有水，师；君子以容民畜众。',
    symbol: '䷆',
    palace: '010010',
    wuxing: '水',
    shi: 2,
    ying: 5,
    ganzhi: ['戊寅', '戊辰', '戊午', '癸丑', '癸亥', '癸酉'],
    relation: ['子孙', '官鬼', '妻财', '官鬼', '兄弟', '父母'],
    judgement: '师：贞，丈人吉，无咎。',
    lineTexts: [
      { label: '初六', text: '师出以律，否臧凶。' },
      { label: '九二', text: '在师中，吉，无咎；王三锡命。' },
      { label: '六三', text: '师或舆尸，凶。' },
      { label: '六四', text: '师左次，无咎。' },
      { label: '六五', text: '田有禽，利执言，无咎；长子帅师，弟子舆尸，贞凶。' },
      { label: '上六', text: '大君有命，开国承家，小人勿用。' },
    ],
  },
  '000010': {
    key: '000010',
    gua: '比',
    name: '水地比',
    sequence: 8,
    text: '地上有水，比；先王以建万国，亲诸侯。',
    symbol: '䷇',
    palace: '000000',
    wuxing: '土',
    shi: 2,
    ying: 5,
    ganzhi: ['乙未', '乙巳', '乙卯', '戊申', '戊戌', '戊子'],
    relation: ['兄弟', '父母', '官鬼', '子孙', '兄弟', '妻财'],
    judgement: '比：吉。原筮，元永贞，无咎。不宁方来，后夫凶。',
    lineTexts: [
      { label: '初六', text: '有孚比之，无咎。有孚盈缶，终来有它吉。' },
      { label: '六二', text: '比之自内，贞吉。' },
      { label: '六三', text: '比之匪人。' },
      { label: '六四', text: '外比之，贞吉。' },
      { label: '九五', text: '显比，王用三驱，失前禽。邑人不诫，吉。' },
      { label: '上六', text: '比之无首，凶。' },
    ],
  },
  '000111': {
    key: '000111',
    gua: '否',
    name: '地天否',
    sequence: 12,
    text: '天地不交，否；君子以俭德辟难，不可荣以禄。',
    symbol: '䷋',
    palace: '111111',
    wuxing: '金',
    shi: 2,
    ying: 5,
    ganzhi: ['乙未', '乙巳', '乙卯', '壬午', '壬申', '壬戌'],
    relation: ['父母', '官鬼', '妻财', '官鬼', '兄弟', '父母'],
    judgement: '否：否之匪人，不利君子贞，大往小来。',
    lineTexts: [
      { label: '初六', text: '拔茅茹，以其汇，贞吉，亨。' },
      { label: '六二', text: '包承，小人吉，大人否，亨。' },
      { label: '六三', text: '包羞。' },
      { label: '九四', text: '有命，无咎，畴离祉。' },
      { label: '九五', text: '休否，大人吉。其亡其亡，系于苞桑。' },
      { label: '上九', text: '倾否，先否后喜。' },
    ],
  },
  '001000': {
    key: '001000',
    gua: '谦',
    name: '地山谦',
    sequence: 15,
    text: '地中有山，谦；君子以裒多益寡，称物平施。',
    symbol: '䷎',
    palace: '110110',
    wuxing: '金',
    shi: 4,
    ying: 1,
    ganzhi: ['丙辰', '丙午', '丙申', '癸丑', '癸亥', '癸酉'],
    relation: ['父母', '官鬼', '兄弟', '父母', '子孙', '兄弟'],
    judgement: '谦：亨，君子有终。',
    lineTexts: [
      { label: '初六', text: '谦谦君子，用涉大川，吉。' },
      { label: '六二', text: '鸣谦，贞吉。' },
      { label: '九三', text: '劳谦，君子有终，吉。' },
      { label: '六四', text: '无不利，㧑谦。' },
      { label: '六五', text: '不富以其邻，利用侵伐，无不利。' },
      { label: '上六', text: '鸣谦，利用行师，征邑国。' },
    ],
  },
  '000100': {
    key: '000100',
    gua: '豫',
    name: '雷地豫',
    sequence: 16,
    text: '雷出地奋，豫；先王以作乐崇德，殷荐之上帝，以配祖考。',
    symbol: '䷏',
    palace: '100100',
    wuxing: '木',
    shi: 0,
    ying: 3,
    ganzhi: ['乙未', '乙巳', '乙卯', '庚午', '庚申', '庚戌'],
    relation: ['妻财', '子孙', '兄弟', '子孙', '官鬼', '妻财'],
    judgement: '豫：利建侯，行师。',
    lineTexts: [
      { label: '初六', text: '鸣豫，凶。' },
      { label: '六二', text: '介于石，不终日，贞吉。' },
      { label: '六三', text: '盱豫，悔。迟有悔。' },
      { label: '九四', text: '由豫，大有得。勿疑。朋盍簪。' },
      { label: '六五', text: '贞疾，恒不死。' },
      { label: '上六', text: '冥豫，成有渝，无咎。' },
    ],
  },
  '011001': {
    key: '011001',
    gua: '蛊',
    name: '山风蛊',
    sequence: 18,
    text: '山下有风，蛊；君子以振民育德。',
    symbol: '䷑',
    palace: '011011',
    wuxing: '木',
    shi: 2,
    ying: 5,
    ganzhi: ['辛丑', '辛亥', '辛酉', '丙戌', '丙子', '丙寅'],
    relation: ['妻财', '父母', '官鬼', '妻财', '父母', '兄弟'],
    judgement: '蛊：元亨，利涉大川。先甲三日，后甲三日。',
    lineTexts: [
      { label: '初六', text: '干父之蛊，有子，考无咎，厉终吉。' },
      { label: '九二', text: '干母之蛊，不可贞。' },
      { label: '九三', text: '干父之蛊，小有悔，无大咎。' },
      { label: '六四', text: '裕父之蛊，往见吝。' },
      { label: '六五', text: '干父之蛊，用誉。' },
      { label: '上九', text: '不事王侯，高尚其事。' },
    ],
  },
  '000011': {
    key: '000011',
    gua: '观',
    name: '风地观',
    sequence: 20,
    text: '风行地上，观；先王以省方观民设教。',
    symbol: '䷓',
    palace: '111111',
    wuxing: '金',
    shi: 3,
    ying: 0,
    ganzhi: ['乙未', '乙巳', '乙卯', '辛未', '辛巳', '辛卯'],
    relation: ['父母', '官鬼', '妻财', '父母', '官鬼', '妻财'],
    judgement: '观：盥而不荐，有孚颙若。',
    lineTexts: [
      { label: '初六', text: '童观，小人无咎，君子吝。' },
      { label: '六二', text: '窥观，利女贞。' },
      { label: '六三', text: '观我生，进退。' },
      { label: '六四', text: '观国之光，利用宾于王。' },
      { label: '九五', text: '观我生，君子无咎。' },
      { label: '上九', text: '观其生，君子无咎。' },
    ],
  },
  '000001': {
    key: '000001',
    gua: '剥',
    name: '山地剥',
    sequence: 23,
    text: '山附于地，剥；上以厚下安宅。',
    symbol: '䷖',
    palace: '111111',
    wuxing: '金',
    shi: 4,
    ying: 1,
    ganzhi: ['乙未', '乙巳', '乙卯', '丙戌', '丙子', '丙寅'],
    relation: ['父母', '官鬼', '妻财', '父母', '子孙', '妻财'],
    judgement: '剥：不利有攸往。',
    lineTexts: [
      { label: '初六', text: '剥床以足，蔑贞，凶。' },
      { label: '六二', text: '剥床以辨，蔑贞，凶。' },
      { label: '六三', text: '剥之，无咎。' },
      { label: '六四', text: '剥床以肤，凶。' },
      { label: '六五', text: '贯鱼，以宫人宠，无不利。' },
      { label: '上九', text: '硕果不食，君子得舆，小人剥庐。' },
    ],
  },
  '011110': {
    key: '011110',
    gua: '大过',
    name: '泽风大过',
    sequence: 28,
    text: '泽灭木，大过；君子以独立不惧，遯世无闷。',
    symbol: '䷛',
    palace: '100100',
    wuxing: '木',
    shi: 3,
    ying: 0,
    ganzhi: ['辛丑', '辛亥', '辛酉', '丁亥', '丁酉', '丁未'],
    relation: ['妻财', '父母', '官鬼', '父母', '官鬼', '妻财'],
    judgement: '大过：栋桡，利有攸往，亨。',
    lineTexts: [
      { label: '初六', text: '藉用白茅，无咎。' },
      { label: '九二', text: '枯杨生稊，老夫得其女妻，无不利。' },
      { label: '九三', text: '栋桡，凶。' },
      { label: '九四', text: '栋隆，吉。有它吝。' },
      { label: '九五', text: '枯杨生华，老妇得其士夫，无咎无誉。' },
      { label: '上六', text: '过涉灭顶，凶，无咎。' },
    ],
  },
  '010010': {
    key: '010010',
    gua: '坎',
    name: '坎为水',
    sequence: 29,
    text: '水洊至，习坎；君子以常德行，习教事。',
    symbol: '䷜',
    palace: '010010',
    wuxing: '水',
    shi: 5,
    ying: 2,
    ganzhi: ['戊寅', '戊辰', '戊午', '戊申', '戊戌', '戊子'],
    relation: ['子孙', '官鬼', '妻财', '父母', '官鬼', '兄弟'],
    judgement: '坎：习坎，有孚，维心亨，行有尚。',
    lineTexts: [
      { label: '初六', text: '习坎，入于坎窞，凶。' },
      { label: '九二', text: '坎有险，求小得。' },
      { label: '六三', text: '来之坎坎，险且枕，入于坎窞，勿用。' },
      { label: '六四', text: '樽酒簋贰，用缶，纳约自牖，终无咎。' },
      { label: '九五', text: '坎不盈，祗既平，无咎。' },
      { label: '上六', text: '系用徽纆，寘于丛棘，三岁不得，凶。' },
    ],
  },
  '001110': {
    key: '001110',
    gua: '咸',
    name: '泽山咸',
    sequence: 31,
    text: '山上有泽，咸；君子以虚受人。',
    symbol: '䷞',
    palace: '110110',
    wuxing: '金',
    shi: 2,
    ying: 5,
    ganzhi: ['丙辰', '丙午', '丙申', '丁亥', '丁酉', '丁未'],
    relation: ['父母', '官鬼', '兄弟', '子孙', '兄弟', '父母'],
    judgement: '咸：亨，利贞，取女吉。',
    lineTexts: [
      { label: '初六', text: '咸其拇。' },
      { label: '六二', text: '咸其腓，凶，居吉。' },
      { label: '九三', text: '咸其股，执其随，往吝。' },
      { label: '九四', text: '贞吉，悔亡。憧憧往来，朋从尔思。' },
      { label: '九五', text: '咸其脢，无悔。' },
      { label: '上六', text: '咸其辅颊舌。' },
    ],
  },
  '011100': {
    key: '011100',
    gua: '恒',
    name: '雷风恒',
    sequence: 32,
    text: '雷风，恒；君子以立不易方。',
    symbol: '䷟',
    palace: '100100',
    wuxing: '木',
    shi: 2,
    ying: 5,
    ganzhi: ['辛丑', '辛亥', '辛酉', '庚午', '庚申', '庚戌'],
    relation: ['妻财', '父母', '官鬼', '子孙', '官鬼', '妻财'],
    judgement: '恒：亨，无咎，利贞，利有攸往。',
    lineTexts: [
      { label: '初六', text: '浚恒，贞凶，无攸利。' },
      { label: '九二', text: '悔亡。' },
      { label: '九三', text: '不恒其德，或承之羞，贞吝。' },
      { label: '九四', text: '田无禽。' },
      { label: '六五', text: '恒其德，贞，妇人吉，夫子凶。' },
      { label: '上六', text: '振恒，凶。' },
    ],
  },
  '001111': {
    key: '001111',
    gua: '遯',
    name: '天山遯',
    sequence: 33,
    text: '天下有山，遁；君子以远小人，不恶而严。',
    symbol: '䷠',
    palace: '111111',
    wuxing: '金',
    shi: 1,
    ying: 4,
    ganzhi: ['丙辰', '丙午', '丙申', '壬午', '壬申', '壬戌'],
    relation: ['父母', '官鬼', '兄弟', '官鬼', '兄弟', '父母'],
    judgement: '遁：亨，小利贞。',
    lineTexts: [
      { label: '初六', text: '遁尾，厉，勿用有攸往。' },
      { label: '六二', text: '执之用黄牛之革，莫之胜说。' },
      { label: '九三', text: '系遁，有疾厉，畜臣妾吉。' },
      { label: '九四', text: '好遁，君子吉，小人否。' },
      { label: '九五', text: '嘉遁，贞吉。' },
      { label: '上九', text: '肥遁，无不利。' },
    ],
  },
  '000101': {
    key: '000101',
    gua: '晋',
    name: '火地晋',
    sequence: 35,
    text: '明出地上，晋；君子以自昭明德。',
    symbol: '䷢',
    palace: '111111',
    wuxing: '金',
    shi: 3,
    ying: 0,
    ganzhi: ['乙未', '乙巳', '乙卯', '己酉', '己未', '己巳'],
    relation: ['父母', '官鬼', '妻财', '兄弟', '父母', '官鬼'],
    judgement: '晋：康侯用锡马蕃庶，昼日三接。',
    lineTexts: [
      { label: '初六', text: '晋如，摧如，贞吉。罔孚，裕无咎。' },
      { label: '六二', text: '晋如，愁如，贞吉。受兹介福，于其王母。' },
      { label: '六三', text: '众允，悔亡。' },
      { label: '九四', text: '晋如鼫鼠，贞厉。' },
      { label: '六五', text: '悔亡，失得勿恤，往吉，无不利。' },
      { label: '上九', text: '晋其角，维用伐邑，厉吉，无咎，贞吝。' },
    ],
  },
  '001010': {
    key: '001010',
    gua: '蹇',
    name: '水山蹇',
    sequence: 39,
    text: '山上有水，蹇；君子以反身修德。',
    symbol: '䷦',
    palace: '110110',
    wuxing: '金',
    shi: 3,
    ying: 0,
    ganzhi: ['丙辰', '丙午', '丙申', '戊申', '戊戌', '戊子'],
    relation: ['父母', '官鬼', '兄弟', '兄弟', '父母', '子孙'],
    judgement: '蹇：利西南，不利东北；利见大人，贞吉。',
    lineTexts: [
      { label: '初六', text: '往蹇，来誉。' },
      { label: '六二', text: '王臣蹇蹇，匪躬之故。' },
      { label: '九三', text: '往蹇，来反。' },
      { label: '六四', text: '往蹇，来连。' },
      { label: '九五', text: '大蹇，朋来。' },
      { label: '上六', text: '往蹇，来硕；吉；利见大人。' },
    ],
  },
  '010100': {
    key: '010100',
    gua: '解',
    name: '雷水解',
    sequence: 40,
    text: '雷雨作，解；君子以赦过宥罪。',
    symbol: '䷧',
    palace: '100100',
    wuxing: '木',
    shi: 1,
    ying: 4,
    ganzhi: ['戊寅', '戊辰', '戊午', '庚午', '庚申', '庚戌'],
    relation: ['兄弟', '妻财', '子孙', '子孙', '官鬼', '妻财'],
    judgement: '解：利西南，无所往，其来复吉；有攸往，夙吉。',
    lineTexts: [
      { label: '初六', text: '无咎。' },
      { label: '九二', text: '田获三狐，得黄矢，贞吉。' },
      { label: '六三', text: '负且乘，致寇至，贞吝。' },
      { label: '九四', text: '解而拇，朋至斯孚。' },
      { label: '六五', text: '君子维有解，吉；有孚于小人。' },
      { label: '上六', text: '公用射隼于高墉之上，获之，无不利。' },
    ],
  },
  '011111': {
    key: '011111',
    gua: '姤',
    name: '天风姤',
    sequence: 44,
    text: '天下有风，姤；后以施命诰四方。',
    symbol: '䷫',
    palace: '111111',
    wuxing: '金',
    shi: 0,
    ying: 3,
    ganzhi: ['辛丑', '辛亥', '辛酉', '壬午', '壬申', '壬戌'],
    relation: ['父母', '子孙', '兄弟', '官鬼', '兄弟', '父母'],
    judgement: '姤：女壮，勿用取女。',
    lineTexts: [
      { label: '初六', text: '系于金柅，贞吉。有攸往，见凶，羸豕孚蹢躅。' },
      { label: '九二', text: '包有鱼，无咎，不利宾。' },
      { label: '九三', text: '臀无肤，其行次且，厉，无大咎。' },
      { label: '九四', text: '包无鱼，起凶。' },
      { label: '九五', text: '以杞包瓜，含章，有陨自天。' },
      { label: '上九', text: '姤其角，吝，无咎。' },
    ],
  },
  '000110': {
    key: '000110',
    gua: '萃',
    name: '泽地萃',
    sequence: 45,
    text: '泽上于地，萃；君子以除戎器，戒不虞。',
    symbol: '䷬',
    palace: '110110',
    wuxing: '金',
    shi: 1,
    ying: 4,
    ganzhi: ['乙未', '乙巳', '乙卯', '丁亥', '丁酉', '丁未'],
    relation: ['父母', '官鬼', '妻财', '子孙', '兄弟', '父母'],
    judgement: '萃：亨。王假有庙，利见大人，亨，利贞。用大牲吉，利有攸往。',
    lineTexts: [
      { label: '初六', text: '有孚不终，乃乱乃萃，若号一握为笑，勿恤，往无咎。' },
      { label: '六二', text: '引吉，无咎，孚乃利用禴。' },
      { label: '六三', text: '萃如，嗟如，无攸利，往无咎，小吝。' },
      { label: '九四', text: '大吉，无咎。' },
      { label: '九五', text: '萃有位，无咎。匪孚，元永贞，悔亡。' },
      { label: '上六', text: '赍咨涕洟，无咎。' },
    ],
  },
  '011000': {
    key: '011000',
    gua: '升',
    name: '地风升',
    sequence: 46,
    text: '地中生木，升；君子以顺德，积小以高大。',
    symbol: '䷭',
    palace: '100100',
    wuxing: '木',
    shi: 3,
    ying: 0,
    ganzhi: ['辛丑', '辛亥', '辛酉', '癸丑', '癸亥', '癸酉'],
    relation: ['妻财', '父母', '官鬼', '妻财', '父母', '官鬼'],
    judgement: '升：元亨，用见大人，勿恤，南征吉。',
    lineTexts: [
      { label: '初六', text: '允升，大吉。' },
      { label: '九二', text: '孚乃利用禴，无咎。' },
      { label: '九三', text: '升虚邑。' },
      { label: '六四', text: '王用亨于岐山，吉，无咎。' },
      { label: '六五', text: '贞吉，升阶。' },
      { label: '上六', text: '冥升，利于不息之贞。' },
    ],
  },
  '010110': {
    key: '010110',
    gua: '困',
    name: '泽水困',
    sequence: 47,
    text: '泽无水，困；君子以致命遂志。',
    symbol: '䷮',
    palace: '110110',
    wuxing: '金',
    shi: 0,
    ying: 3,
    ganzhi: ['戊寅', '戊辰', '戊午', '丁亥', '丁酉', '丁未'],
    relation: ['妻财', '父母', '官鬼', '子孙', '兄弟', '父母'],
    judgement: '困：亨，贞，大人吉，无咎。有言不信。',
    lineTexts: [
      { label: '初六', text: '臀困于株木，入于幽谷，三岁不觌。' },
      { label: '九二', text: '困于酒食，朱绂方来，利用享祀，征凶，无咎。' },
      { label: '六三', text: '困于石，据于蒺藜，入于其宫，不见其妻，凶。' },
      { label: '九四', text: '来徐徐，困于金车，吝，有终。' },
      { label: '九五', text: '劓刖，困于赤绂，乃徐有说，利用祭祀。' },
      { label: '上六', text: '困于葛藟，于臲卼，曰动悔。有悔，征吉。' },
    ],
  },
  '011010': {
    key: '011010',
    gua: '井',
    name: '水风井',
    sequence: 48,
    text: '木上有水，井；君子以劳民劝相。',
    symbol: '䷯',
    palace: '100100',
    wuxing: '木',
    shi: 4,
    ying: 1,
    ganzhi: ['辛丑', '辛亥', '辛酉', '戊申', '戊戌', '戊子'],
    relation: ['妻财', '父母', '官鬼', '官鬼', '妻财', '父母'],
    judgement: '井：改邑不改井，无丧无得，往来井井。汔至亦未繘井，羸其瓶，凶。',
    lineTexts: [
      { label: '初六', text: '井泥不食，旧井无禽。' },
      { label: '九二', text: '井谷射鲋，瓮敝漏。' },
      { label: '九三', text: '井渫不食，为我心恻；可用汲，王明，并受其福。' },
      { label: '六四', text: '井甃，无咎。' },
      { label: '九五', text: '井洌，寒泉食。' },
      { label: '上六', text: '井收勿幕，有孚元吉。' },
    ],
  },
  '011101': {
    key: '011101',
    gua: '鼎',
    name: '火风鼎',
    sequence: 50,
    text: '木上有火，鼎；君子以正位凝命。',
    symbol: '䷱',
    palace: '101101',
    wuxing: '火',
    shi: 1,
    ying: 4,
    ganzhi: ['辛丑', '辛亥', '辛酉', '己酉', '己未', '己巳'],
    relation: ['子孙', '官鬼', '妻财', '妻财', '子孙', '兄弟'],
    judgement: '鼎：元吉，亨。',
    lineTexts: [
      { label: '初六', text: '鼎颠趾，利出否。得妾以其子，无咎。' },
      { label: '九二', text: '鼎有实，我仇有疾，不我能即，吉。' },
      { label: '九三', text: '鼎耳革，其行塞，雉膏不食，方雨亏悔，终吉。' },
      { label: '九四', text: '鼎折足，覆公餗，其形渥，凶。' },
      { label: '六五', text: '鼎黄耳金铉，利贞。' },
      { label: '上九', text: '鼎玉铉，大吉，无不利。' },
    ],
  },
  '001001': {
    key: '001001',
    gua: '艮',
    name: '艮为山',
    sequence: 52,
    text: '兼山，艮；君子以思不出其位。',
    symbol: '䷳',
    palace: '001001',
    wuxing: '土',
    shi: 5,
    ying: 2,
    ganzhi: ['丙辰', '丙午', '丙申', '丙戌', '丙子', '丙寅'],
    relation: ['兄弟', '父母', '子孙', '兄弟', '妻财', '官鬼'],
    judgement: '艮：艮其背，不获其身；行其庭，不见其人，无咎。',
    lineTexts: [
      { label: '初六', text: '艮其趾，无咎，利永贞。' },
      { label: '六二', text: '艮其腓，不拯其随，其心不快。' },
      { label: '九三', text: '艮其限，列其夤，厉薰心。' },
      { label: '六四', text: '艮其身，无咎。' },
      { label: '六五', text: '艮其辅，言有序，悔亡。' },
      { label: '上九', text: '敦艮，吉。' },
    ],
  },
  '001011': {
    key: '001011',
    gua: '渐',
    name: '风山渐',
    sequence: 53,
    text: '山上有木，渐；君子以居贤德，善俗。',
    symbol: '䷴',
    palace: '001001',
    wuxing: '土',
    shi: 2,
    ying: 5,
    ganzhi: ['丙辰', '丙午', '丙申', '辛未', '辛巳', '辛卯'],
    relation: ['兄弟', '父母', '子孙', '兄弟', '父母', '官鬼'],
    judgement: '渐：女归吉，利贞。',
    lineTexts: [
      { label: '初六', text: '鸿渐于干，小子厉，有言，无咎。' },
      { label: '六二', text: '鸿渐于磐，饮食衎衎，吉。' },
      { label: '九三', text: '鸿渐于陆，夫征不复，妇孕不育，凶；利御寇。' },
      { label: '六四', text: '鸿渐于木，或得其桷，无咎。' },
      { label: '九五', text: '鸿渐于陵，妇三岁不孕，终莫之胜，吉。' },
      { label: '上九', text: '鸿渐于陆，其羽可用为仪，吉。' },
    ],
  },
  '001101': {
    key: '001101',
    gua: '旅',
    name: '火山旅',
    sequence: 56,
    text: '山上有火，旅；君子以明慎用刑，而不留狱。',
    symbol: '䷷',
    palace: '101101',
    wuxing: '火',
    shi: 0,
    ying: 3,
    ganzhi: ['丙辰', '丙午', '丙申', '己酉', '己未', '己巳'],
    relation: ['子孙', '兄弟', '妻财', '妻财', '子孙', '兄弟'],
    judgement: '旅：小亨，旅贞吉。',
    lineTexts: [
      { label: '初六', text: '旅琐琐，斯其所取灾。' },
      { label: '六二', text: '旅即次，怀其资，得童仆，贞。' },
      { label: '九三', text: '旅焚其次，丧其童仆，贞厉。' },
      { label: '九四', text: '旅于处，得其资斧，我心不快。' },
      { label: '六五', text: '射雉一矢亡，终以誉命。' },
      { label: '上九', text: '鸟焚其巢，旅人先笑后号啕。丧牛于易，凶。' },
    ],
  },
  '011011': {
    key: '011011',
    gua: '风',
    name: '巽为风',
    sequence: 57,
    text: '随风，巽；君子以申命行事。',
    symbol: '䷸',
    palace: '011011',
    wuxing: '木',
    shi: 5,
    ying: 2,
    ganzhi: ['辛丑', '辛亥', '辛酉', '辛未', '辛巳', '辛卯'],
    relation: ['妻财', '父母', '官鬼', '妻财', '子孙', '兄弟'],
    judgement: '巽：小亨，利有攸往，利见大人。',
    lineTexts: [
      { label: '初六', text: '进退，利武人之贞。' },
      { label: '九二', text: '巽在床下，用史巫纷若，吉，无咎。' },
      { label: '九三', text: '频巽，吝。' },
      { label: '六四', text: '悔亡，田获三品。' },
      { label: '九五', text: '贞吉，悔亡，无不利。无初有终，先庚三日，后庚三日，吉。' },
      { label: '上九', text: '巽在床下，丧其资斧，贞凶。' },
    ],
  },
  '010011': {
    key: '010011',
    gua: '涣',
    name: '风水涣',
    sequence: 59,
    text: '风行水上，涣；先王以享于帝，立庙。',
    symbol: '䷺',
    palace: '101101',
    wuxing: '火',
    shi: 4,
    ying: 1,
    ganzhi: ['戊寅', '戊辰', '戊午', '辛未', '辛巳', '辛卯'],
    relation: ['父母', '子孙', '兄弟', '子孙', '兄弟', '父母'],
    judgement: '涣：亨。王假有庙，利涉大川，利贞。',
    lineTexts: [
      { label: '初六', text: '用拯马壮，吉。' },
      { label: '九二', text: '涣奔其机，悔亡。' },
      { label: '六三', text: '涣其躬，无悔。' },
      { label: '六四', text: '涣其群，元吉；涣有丘，匪夷所思。' },
      { label: '九五', text: '涣汗其大号，涣王居，无咎。' },
      { label: '上九', text: '涣其血，去逖出，无咎。' },
    ],
  },
  '001100': {
    key: '001100',
    gua: '小过',
    name: '雷山小过',
    sequence: 62,
    text: '山上有雷，小过；君子以行过乎恭，丧过乎哀，用过乎俭。',
    symbol: '䷽',
    palace: '110110',
    wuxing: '金',
    shi: 3,
    ying: 0,
    ganzhi: ['丙辰', '丙午', '丙申', '庚午', '庚申', '庚戌'],
    relation: ['父母', '官鬼', '兄弟', '官鬼', '兄弟', '父母'],
    judgement: '小过：亨，利贞，可小事，不可大事。飞鸟遗之音，不宜上，宜下，大吉。',
    lineTexts: [
      { label: '初六', text: '飞鸟以凶。' },
      { label: '六二', text: '过其祖，遇其妣；不及其君，遇其臣；无咎。' },
      { label: '九三', text: '弗过防之，从或戕之，凶。' },
      { label: '九四', text: '无咎。弗过遇之；往厉必戒，勿用永贞。' },
      { label: '六五', text: '密云不雨，自我西郊；公弋取彼在穴。' },
      { label: '上六', text: '弗遇过之，飞鸟离之，凶，是谓灾眚。' },
    ],
  },
  '010101': {
    key: '010101',
    gua: '未济',
    name: '火水未济',
    sequence: 64,
    text: '火在水上，未济；君子以慎辨物居方。',
    symbol: '䷿',
    palace: '101101',
    wuxing: '火',
    shi: 2,
    ying: 5,
    ganzhi: ['戊寅', '戊辰', '戊午', '己酉', '己未', '己巳'],
    relation: ['父母', '子孙', '兄弟', '妻财', '子孙', '兄弟'],
    judgement: '未济：亨，小狐汔济，濡其尾，无攸利。',
    lineTexts: [
      { label: '初六', text: '濡其尾，吝。' },
      { label: '九二', text: '曳其轮，贞吉。' },
      { label: '六三', text: '未济，征凶，利涉大川。' },
      { label: '九四', text: '贞吉，悔亡，震用伐鬼方，三年有赏于大国。' },
      { label: '六五', text: '贞吉，无悔，君子之光，有孚吉。' },
      { label: '上九', text: '有孚于饮酒，无咎，濡其首，有孚失是。' },
    ],
  },
};
